language: ruby
rvm:
  - 2.1.5
sudo: false
cache: bundler
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database quizzer_test;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bundle exec rspec spec
env:
  MAILER_HOST=localhost:52662