version: 2
jobs:
  build:
    parallelism: 4
    working_directory: ~/quizzer
    docker:
      - image: circleci/ruby:2.1.5-node-browsers
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          PGHOST: localhost
          PGUSER: postgres
      - image: circleci/postgres:9.6.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: quizzer_test
    steps:
      - checkout

      - restore_cache:
          key: quizzer-app-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - save_cache:
          key: quizzer-app-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database setup
          command: bundle exec rake db:create db:schema:load --trace

      - run:
          name: Create the screenshot artifact directory
          command: mkdir -p /tmp/capybara;

      - run: |
          bundle exec rspec -r rspec_junit_formatter \
                            --format RspecJunitFormatter \
                            --out ~/quizzer/tmp/test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings --timings-type=classname)
      # Save artifacts
      - store_test_results:
          path: ~/quizzer/tmp/test-results
      - store_artifacts:
          path: ~/quizzer/tmp/test-results
      - store_artifacts:
          path: ~/quizzer/tmp/capybara
  # deploy:
  #   machine:
  #       enabled: true
  #   working_directory: ~/quizzer
  #   environment:
  #     HEROKU_APP: "squizzer"
  #   steps:
  #     - checkout
  #     - run:
  #         name: Setup Heroku
  #         command: bash .circleci/setup-heroku.sh

  #     - run:
  #         command: |
  #           heroku maintenance:on
  #           git push --force git@heroku.com:$HEROKU_APP.git $CIRCLE_SHA1:refs/heads/master
  #           heroku run rake db:migrate
  #           heroku maintenance:off
  #           sleep 5 # sleep for 5 seconds to wait for dynos
  #           heroku restart