AccessModifierIndentation:
  Description: Check indentation of private/protected visibility modifiers.
  Enabled: false
Blocks:
  Description: >-
                Avoid using {...} for multi-line blocks (multiline chaining is
                always ugly).
                Prefer {...} over do...end for single-line blocks.
  Enabled: true
StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true